<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_mailchimp_plugin.validator.unique_newsletter_email_validator' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidator.php';
include_once $this->targetDirs[3].'/vendor/bitbag/mailchimp-plugin/src/Validator/Constraints/UniqueNewsletterEmailValidator.php';

return $this->privates['bitbag_sylius_mailchimp_plugin.validator.unique_newsletter_email_validator'] = new \BitBag\SyliusMailChimpPlugin\Validator\Constraints\UniqueNewsletterEmailValidator(($this->services['sylius.repository.customer'] ?? $this->load('getSylius_Repository_CustomerService.php')));
