<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_mailchimp_plugin.event_listener.customer_listener' shared service.

include_once $this->targetDirs[3].'/vendor/bitbag/mailchimp-plugin/src/EventListener/CustomerNewsletterListener.php';
include_once $this->targetDirs[3].'/vendor/bitbag/mailchimp-plugin/src/Handler/NewsletterSubscriptionHandler.php';
include_once $this->targetDirs[3].'/vendor/drewm/mailchimp-api/src/MailChimp.php';

return $this->privates['bitbag_sylius_mailchimp_plugin.event_listener.customer_listener'] = new \BitBag\SyliusMailChimpPlugin\EventListener\CustomerNewsletterListener(new \BitBag\SyliusMailChimpPlugin\Handler\NewsletterSubscriptionHandler(($this->services['sylius.repository.customer'] ?? $this->load('getSylius_Repository_CustomerService.php')), ($this->services['sylius.factory.customer'] ?? $this->services['sylius.factory.customer'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Core\\Model\\Customer')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), new \DrewM\MailChimp\MailChimp(NULL), NULL));
