<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKEvhMO7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKEvhMO7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKEvhMO7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKEvhMO7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKEvhMO7\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KEvhMO7',
    'container.build_id' => '8fc8bdb8',
    'container.build_time' => 1539604347,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKEvhMO7');
