<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5EWql8y\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5EWql8y/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5EWql8y.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5EWql8y\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container5EWql8y\srcDevDebugProjectContainer(array(
    'container.build_hash' => '5EWql8y',
    'container.build_id' => 'd1a196e4',
    'container.build_time' => 1539262905,
), __DIR__.\DIRECTORY_SEPARATOR.'Container5EWql8y');
